#!/usr/bin/env bash
#
# scripts/generate-arch-docs.sh — deterministic architecture documentation generator.
#
# Scans the repo for function definitions:
#   shell:      *.sh files and extensionless bin/* helpers
#   TypeScript: app/server/** and app/src/** (*.ts, *.tsx, *.js, *.jsx, *.mts, *.cts)
#   Rust:       app/src-tauri/src/**/*.rs
#
# For each function records: name, file (repo-relative), line, signature (the
# full definition line, trimmed), calls (other repo-defined function names
# textually referenced in its body = lines up to the next definition in the
# same file; sorted, unique), and tags from deterministic name/file/signature
# heuristics.
#
# Emits:
#   docs/architecture/functions.json
#   docs/architecture/functions.md
#   docs/architecture/architecture.md
# and scaffolds docs/architecture/functions-intent.md ONLY if it is missing
# (that file is model-written and is never regenerated).
#
# Deterministic: no LLM, no network. generated_at comes from the source
# commit's date, every list is sorted under LC_ALL=C, and only tracked files
# (git ls-files) are parsed, so output is byte-identical for a given commit.
# Exits non-zero with a clear error if parsing fails.
#
# Usage: bash scripts/generate-arch-docs.sh   (run from anywhere inside the repo)

set -euo pipefail
export LC_ALL=C

VERSION="1.0.0"
REPO_NAME="cockpit"
OUT_DIR="docs/architecture"

log() { printf 'generate-arch-docs.sh: %s\n' "$*"; }
err() { printf 'generate-arch-docs.sh: ERROR: %s\n' "$*" >&2; }

# ---------------------------------------------------------------- repo context
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
[ -n "$REPO_ROOT" ] || { err "not inside a git repository"; exit 1; }
cd "$REPO_ROOT"

SOURCE_COMMIT="$(git rev-parse HEAD 2>/dev/null || true)"
[ -n "$SOURCE_COMMIT" ] || { err "cannot resolve HEAD to a commit"; exit 1; }
COMMIT_EPOCH="$(git show -s --format=%ct "$SOURCE_COMMIT" 2>/dev/null || true)"
[ -n "$COMMIT_EPOCH" ] || { err "cannot read commit date for $SOURCE_COMMIT"; exit 1; }
GENERATED_AT="$(date -u -d "@$COMMIT_EPOCH" +%Y-%m-%dT%H:%M:%SZ)"
COMMIT_DATE="$(date -u -d "@$COMMIT_EPOCH" +%Y-%m-%d)"

mkdir -p "$OUT_DIR"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

HEADER="<!-- GENERATED by scripts/generate-arch-docs.sh v$VERSION from commit $SOURCE_COMMIT ($GENERATED_AT). DO NOT EDIT — regenerate. Model-written intents: functions-intent.md -->"

# ------------------------------------------------------- 1. collect source files
# Tracked files only: deterministic per commit, ignores untracked scratch.
git ls-files | sort > "$TMP/tracked.txt"
[ -s "$TMP/tracked.txt" ] || { err "git ls-files returned no files"; exit 1; }

grep -E '\.sh$' "$TMP/tracked.txt" > "$TMP/sh_files.txt" || true
grep -E '^bin/[^/]+$' "$TMP/tracked.txt" | grep -vE '\.[^/]+$' > "$TMP/bin_files.txt" || true
{ cat "$TMP/sh_files.txt" "$TMP/bin_files.txt"; } | sort -u > "$TMP/shell_files.txt"
grep -E '^(app/server|app/src)/.*\.(ts|tsx|js|jsx|mts|cts)$' "$TMP/tracked.txt" > "$TMP/ts_files.txt" || true
grep -E '^app/src-tauri/src/.*\.rs$' "$TMP/tracked.txt" > "$TMP/rs_files.txt" || true

# ---------------------------------------------------------- 2. parse definitions
# TSV columns: file \t line \t name \t lang \t signature

cat > "$TMP/parse_shell.awk" <<'AWK'
{
  if ($0 ~ /^[ \t]*#/) next
  s = $0
  sub(/^[ \t]+/, "", s)
  name = ""
  if (s ~ /^function[ \t]+/) {
    t = s
    sub(/^function[ \t]+/, "", t)
    if (match(t, /^[A-Za-z_][A-Za-z0-9_]*/)) name = substr(t, RSTART, RLENGTH)
  } else if (match(s, /^[A-Za-z_][A-Za-z0-9_]*[ \t]*\(\)/)) {
    t = substr(s, RSTART, RLENGTH)
    sub(/[ \t]*\(\)$/, "", t)
    name = t
  }
  if (name != "") {
    sig = $0
    gsub(/\t/, " ", sig)
    sub(/^[ \t]+/, "", sig)
    sub(/[ \t]+$/, "", sig)
    printf "%s\t%d\t%s\tshell\t%s\n", FILENAME, FNR, name, sig
  }
}
AWK

cat > "$TMP/parse_ts.awk" <<'AWK'
{
  if ($0 ~ /^[ \t]*\/\//) next
  s = $0
  sub(/^[ \t]+/, "", s)
  name = ""
  t = s
  if (t ~ /^export[ \t]+/) sub(/^export[ \t]+/, "", t)
  if (t ~ /^default[ \t]+/) sub(/^default[ \t]+/, "", t)
  if (t ~ /^(async[ \t]+)?function([^A-Za-z0-9_$]|$)/) {
    u = t
    sub(/^(async[ \t]+)?function/, "", u)
    sub(/^[ \t]*\*[ \t]*/, "", u)
    sub(/^[ \t]+/, "", u)
    if (match(u, /^[A-Za-z_$][A-Za-z0-9_$]*/)) name = substr(u, RSTART, RLENGTH)
  } else if (t ~ /^(const|let|var)[ \t]+/) {
    u = t
    sub(/^(const|let|var)[ \t]+/, "", u)
    if (match(u, /^[A-Za-z_$][A-Za-z0-9_$]*/)) {
      nm = substr(u, RSTART, RLENGTH)
      rest = substr(u, RSTART + RLENGTH)
      if (rest ~ /^[ \t]*=[ \t]*(async[ \t]+)?\(/ && t ~ /=>/) name = nm
    }
  } else {
    u = t
    sub(/^async[ \t]+/, "", u)
    if (u ~ /^[A-Za-z_$]/ && u !~ /=>/ && u !~ /=/) {
      if (match(u, /^[A-Za-z_$][A-Za-z0-9_$]*/)) {
        nm = substr(u, RSTART, RLENGTH)
        rest = substr(u, RSTART + RLENGTH)
        if (nm !~ /^(if|for|while|switch|catch|with|do|else|return|typeof|new|class|function|import|export|case|async)$/ && \
            rest ~ /^[ \t]*(<[^;{}]*>)?\([^;{}]*\)[ \t]*(:[^;{}=][^;{}]*)?\{[ \t]*$/) name = nm
      }
    }
  }
  if (name != "") {
    sig = $0
    gsub(/\t/, " ", sig)
    sub(/^[ \t]+/, "", sig)
    sub(/[ \t]+$/, "", sig)
    printf "%s\t%d\t%s\tts\t%s\n", FILENAME, FNR, name, sig
  }
}
AWK

cat > "$TMP/parse_rs.awk" <<'AWK'
{
  if ($0 ~ /^[ \t]*\/\//) next
  s = $0
  sub(/^[ \t]+/, "", s)
  t = s
  changed = 1
  while (changed) {
    changed = 0
    if (t ~ /^(pub([ \t]*\([^)]*\))?|async|unsafe|const|extern([ \t]+"[^"]*")?)[ \t]+/) {
      sub(/^(pub([ \t]*\([^)]*\))?|async|unsafe|const|extern([ \t]+"[^"]*")?)[ \t]+/, "", t)
      changed = 1
    }
  }
  name = ""
  if (t ~ /^fn([^A-Za-z0-9_]|$)/) {
    u = t
    sub(/^fn/, "", u)
    sub(/^[ \t]+/, "", u)
    if (match(u, /^[A-Za-z_][A-Za-z0-9_]*/)) name = substr(u, RSTART, RLENGTH)
  }
  if (name != "") {
    sig = $0
    gsub(/\t/, " ", sig)
    sub(/^[ \t]+/, "", sig)
    sub(/[ \t]+$/, "", sig)
    printf "%s\t%d\t%s\trust\t%s\n", FILENAME, FNR, name, sig
  }
}
AWK

: > "$TMP/defs.tsv"
[ -s "$TMP/shell_files.txt" ] && xargs -r -a "$TMP/shell_files.txt" -d '\n' awk -f "$TMP/parse_shell.awk" >> "$TMP/defs.tsv"
[ -s "$TMP/ts_files.txt" ] && xargs -r -a "$TMP/ts_files.txt" -d '\n' awk -f "$TMP/parse_ts.awk" >> "$TMP/defs.tsv"
[ -s "$TMP/rs_files.txt" ] && xargs -r -a "$TMP/rs_files.txt" -d '\n' awk -f "$TMP/parse_rs.awk" >> "$TMP/defs.tsv"

TAB="$(printf '\t')"
sort -t "$TAB" -k1,1 -k2,2n "$TMP/defs.tsv" > "$TMP/defs_sorted.tsv"

# ---------------------------------------------------------------- 3. load model
declare -a FFILES=() FLINES=() FNAMES=() FLANGS=() FSIGS=()
while IFS="$TAB" read -r f ln nm lg sg; do
  # basic sanity: every row must have all fields
  if [ -z "$f" ] || [ -z "$ln" ] || [ -z "$nm" ] || [ -z "$sg" ]; then
    err "malformed parse row: [$f] [$ln] [$nm] [$sg]"
    exit 1
  fi
  FFILES+=("$f"); FLINES+=("$ln"); FNAMES+=("$nm"); FLANGS+=("$lg"); FSIGS+=("$sg")
done < "$TMP/defs_sorted.tsv"

N=${#FNAMES[@]}
(( N > 0 )) || { err "parsing produced zero functions; refusing to write empty docs"; exit 1; }
log "parsed $N functions"

# executable-bit lookup for the entrypoint tag (git mode 100755)
declare -A FILE_EXEC=()
while read -r mode _ _ f; do
  [ "$mode" = "100755" ] && FILE_EXEC["$f"]=1
done < <(git ls-files -s)

# ------------------------------------------------------------------ 4. tag each
# Canonical tag order: entrypoint network auth privileged user-input
# persistence ipc rendering process-spawn config validation test ; else logic.
compute_tags() {
  local name="$1" file="$2" sig="$3" tags=""
  local lhay lfile
  lhay="$(printf '%s' "$name $file $sig" | tr '[:upper:]' '[:lower:]')"
  lfile="$(printf '%s' "$file" | tr '[:upper:]' '[:lower:]')"

  if [ "$name" = "main" ] || [ "${FILE_EXEC[$file]:-0}" = "1" ]; then tags+="entrypoint "; fi
  case "$lhay" in *listen*|*serve*|*http*|*ws*|*fetch*|*request*|*gateway*) tags+="network ";; esac
  case "$lhay" in *auth*|*login*|*token*|*secret*|*credential*) tags+="auth ";; esac
  case "$lhay" in *sudo*|*setuid*|*chmod*|*chown*|*root*) tags+="privileged ";; esac
  case "$lhay" in *input*|*argv*|*args*|*param*|*prompt*|*flag*|*read*) tags+="user-input ";; esac
  case "$lhay" in *save*|*write*|*store*|*state*|*db*|*persist*|*mkdir*) tags+="persistence ";; esac
  case "$lhay" in *tmux*|*socket*|*pipe*|*ipc*|*message*|*channel*|*signal*) tags+="ipc ";; esac
  case "$lhay" in *render*|*display*|*ui*|*html*|*view*) tags+="rendering ";; esac
  case "$lhay" in *exec*|*spawn*|*popen*|*system*|*command*|*run*) tags+="process-spawn ";; esac
  case "$lhay" in *config*|*env*|*option*|*setting*) tags+="config ";; esac
  case "$lhay" in *valid*|*guard*|*check*|*verify*|*lint*|*audit*) tags+="validation ";; esac
  case "$lfile" in *_test*|*test_*|*spec*) tags+="test ";; esac

  # de-duplicate while preserving canonical order
  local dedup="" t
  for t in $tags; do
    case " $dedup " in *" $t "*) ;; *) dedup="${dedup:+$dedup }$t";; esac
  done
  [ -z "$dedup" ] && dedup="logic"
  printf '%s' "$dedup"
}

declare -a FTAGS=()
for (( k = 0; k < N; k++ )); do
  FTAGS[k]="$(compute_tags "${FNAMES[k]}" "${FFILES[k]}" "${FSIGS[k]}")"
done

# ------------------------------------------------- 5. anchors (github-style)
declare -A ANCHOR_COUNT=()
declare -a FANCHORS=()
for (( k = 0; k < N; k++ )); do
  base="$(printf '%s' "${FNAMES[k]}" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_-')"
  [ -n "$base" ] || base="fn"
  if [ -n "${ANCHOR_COUNT[$base]+x}" ]; then
    ANCHOR_COUNT[$base]=$(( ANCHOR_COUNT[$base] + 1 ))
    FANCHORS[k]="${base}-${ANCHOR_COUNT[$base]}"
  else
    ANCHOR_COUNT[$base]=1
    FANCHORS[k]="$base"
  fi
done

# ------------------------------------------------- 6. calls (textual reference)
printf '%s\n' "${FNAMES[@]}" | sort -u > "$TMP/names.txt"
declare -a FCALLS=()
i=0
while (( i < N )); do
  f="${FFILES[i]}"
  j=$i
  while (( j < N )) && [ "${FFILES[j]}" = "$f" ]; do j=$(( j + 1 )); done
  total_lines="$(wc -l < "$f")"
  for (( k = i; k < j; k++ )); do
    start="${FLINES[k]}"
    if (( k + 1 < j )); then end=$(( FLINES[k+1] - 1 )); else end="$total_lines"; fi
    calls="$(sed -n "${start},${end}p" "$f" \
      | grep -oE '[A-Za-z_$][A-Za-z0-9_$]*' \
      | sort -u \
      | comm -12 "$TMP/names.txt" - \
      | grep -vxF -- "${FNAMES[k]}" || true)"
    FCALLS[k]="$(printf '%s' "$calls" | paste -sd' ' -)"
  done
  i=$j
done

# ------------------------------------------------------------- 7. emit outputs
json_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\t'/\\t}"
  s="${s//$'\r'/\\r}"
  s="$(printf '%s' "$s" | tr -d '\000-\010\013\014\016-\037')"
  printf '%s' "$s"
}

json_str_array() { # space-separated words -> JSON array of strings on one line
  local first=1 w
  printf '['
  for w in $1; do
    if (( first )); then first=0; else printf ', '; fi
    printf '"%s"' "$(json_escape "$w")"
  done
  printf ']'
}

{
  printf '{\n'
  printf '  "generator": "generate-arch-docs.sh",\n'
  printf '  "generator_version": "%s",\n' "$VERSION"
  printf '  "source_commit": "%s",\n' "$SOURCE_COMMIT"
  printf '  "generated_at": "%s",\n' "$GENERATED_AT"
  printf '  "repo": "%s",\n' "$REPO_NAME"
  printf '  "functions": [\n'
  for (( k = 0; k < N; k++ )); do
    printf '    {\n'
    printf '      "name": "%s",\n' "$(json_escape "${FNAMES[k]}")"
    printf '      "file": "%s",\n' "$(json_escape "${FFILES[k]}")"
    printf '      "line": %d,\n' "${FLINES[k]}"
    printf '      "signature": "%s",\n' "$(json_escape "${FSIGS[k]}")"
    printf '      "calls": %s,\n' "$(json_str_array "${FCALLS[k]}")"
    printf '      "tags": %s\n' "$(json_str_array "${FTAGS[k]}")"
    if (( k + 1 < N )); then printf '    },\n'; else printf '    }\n'; fi
  done
  printf '  ]\n'
  printf '}\n'
} > "$OUT_DIR/functions.json"

if command -v python3 >/dev/null 2>&1; then
  python3 -c 'import json,sys; json.load(open(sys.argv[1]))' "$OUT_DIR/functions.json" \
    || { err "functions.json failed JSON validation"; exit 1; }
fi

# component of a file = top-level directory, or "root"
component_of() {
  local f="$1" c="${1%%/*}"
  if [ "$c" = "$f" ]; then printf 'root'; else printf '%s' "$c"; fi
}

md_escape_sig() { printf '`%s`' "$1"; }

{
  printf '%s\n' "$HEADER"
  printf '# Functions — %s\n' "$REPO_NAME"
  printf '\n'
  prev_file=""
  for (( k = 0; k < N; k++ )); do
    f="${FFILES[k]}"
    if [ "$f" != "$prev_file" ]; then
      printf '## %s\n\n' "$f"
      prev_file="$f"
    fi
    printf '### `%s` — line %d\n\n' "${FNAMES[k]}" "${FLINES[k]}"
    printf -- '- signature: %s\n' "$(md_escape_sig "${FSIGS[k]}")"
    tags_md="$(printf '`%s`' "${FTAGS[k]%% *}")"
    rest="${FTAGS[k]#* }"
    if [ "$rest" != "${FTAGS[k]}" ]; then
      for t in $rest; do tags_md+=", \`$t\`"; done
    fi
    printf -- '- tags: %s\n' "$tags_md"
    if [ -n "${FCALLS[k]}" ]; then
      calls_md=""
      for c in ${FCALLS[k]}; do
        [ -n "$calls_md" ] && calls_md+=", "
        calls_md+="\`$c\`"
      done
    else
      calls_md="none"
    fi
    printf -- '- calls: %s\n' "$calls_md"
    printf -- '- component: `%s`\n' "$(component_of "$f")"
    printf -- '- [intent](functions-intent.md#%s)\n' "${FANCHORS[k]}"
    printf '\n'
  done
} > "$OUT_DIR/functions.md"

{
  printf '%s\n' "$HEADER"
  printf '# Architecture — %s\n' "$REPO_NAME"
  printf '\n'
  # components in alphabetical order; functions keep file,line order
  prev_comp=""
  # build component order list
  : > "$TMP/components.txt"
  for (( k = 0; k < N; k++ )); do
    component_of "${FFILES[k]}"
    printf '\n'
  done | sort -u > "$TMP/components.txt"
  while IFS= read -r comp; do
    [ -n "$comp" ] || continue
    printf '## Component: %s\n\n' "$comp"
    for (( k = 0; k < N; k++ )); do
      [ "$(component_of "${FFILES[k]}")" = "$comp" ] || continue
      tags_csv="$(printf '%s' "${FTAGS[k]}" | tr ' ' ',')"
      printf -- '- [[functions.md#%s|%s]] — %s:%d — %s\n' \
        "${FANCHORS[k]}" "${FNAMES[k]}" "${FFILES[k]}" "${FLINES[k]}" "$tags_csv"
    done
    printf '\n'
  done < "$TMP/components.txt"
} > "$OUT_DIR/architecture.md"

# --------------------------------- 8. intent file: scaffold only if missing
# NEVER regenerate this file: it is model-written.
if [ ! -e "$OUT_DIR/functions-intent.md" ]; then
  {
    printf '> MODEL-WRITTEN — not regenerated by scripts/generate-arch-docs.sh. Edit freely.\n'
    printf '\n'
    printf '# Function intents — %s\n' "$REPO_NAME"
    printf '\n'
    printf '| Function | Intent |\n'
    printf '|---|---|\n'
    for (( k = 0; k < N; k++ )); do
      printf '| <a id="%s"></a>`%s` — %s | [auto-scaffold] model-written intent pending. |\n' \
        "${FANCHORS[k]}" "${FNAMES[k]}" "${FFILES[k]}"
    done
  } > "$OUT_DIR/functions-intent.md"
  log "scaffolded $OUT_DIR/functions-intent.md (model-written intents pending)"
else
  log "$OUT_DIR/functions-intent.md exists; left untouched"
fi

log "wrote $OUT_DIR/functions.json, functions.md, architecture.md from commit $SOURCE_COMMIT ($N functions)"
